#!/usr/bin/env bash
# build.sh — combine schemes/ + common/tmux.conf.in into build/tmux.conf.
#
#   ./build.sh [--widget cpu|vms|<name>|none] [--scroll-lines N]
#
#   --scroll-lines N   lines moved per mouse-wheel notch in copy-mode (default 1).
#                      Lower feels calmer on low-latency links.
#
# The per-session accent expression is generated from schemes/*.scheme as a
# nested tmux conditional   #{?#{m:GLOB,#S},ACCENT, ...}   and inlined at every
# @@ACCENT@@ marker in the template (%hidden vars aren't re-evaluated inside
# format strings, so we inline rather than reference). Unknown sessions fall
# through to neutral grey. Lowest ORDER wins (checked first).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCHEMES_DIR="$ROOT/schemes"
TEMPLATE="$ROOT/common/tmux.conf.in"
OUT_DIR="$ROOT/build"
OUT="$OUT_DIR/tmux.conf"
DEFAULT_ACCENT="#928374"   # neutral grey — unknown / unrecognized session

WIDGET="cpu"
SCROLL_LINES="1"   # lines per wheel notch in copy-mode
while [ $# -gt 0 ]; do
  case "$1" in
    --widget)        WIDGET="${2:?--widget needs a value}"; shift 2 ;;
    --widget=*)      WIDGET="${1#*=}"; shift ;;
    --scroll-lines)  SCROLL_LINES="${2:?--scroll-lines needs a value}"; shift 2 ;;
    --scroll-lines=*) SCROLL_LINES="${1#*=}"; shift ;;
    -h|--help)       grep '^#' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "build.sh: unknown arg: $1" >&2; exit 2 ;;
  esac
done

case "$SCROLL_LINES" in
  ''|*[!0-9]*) echo "build.sh: --scroll-lines must be a positive integer (got '$SCROLL_LINES')" >&2; exit 2 ;;
  0) echo "build.sh: --scroll-lines must be >= 1" >&2; exit 2 ;;
esac

[ -f "$TEMPLATE" ] || { echo "build.sh: missing $TEMPLATE" >&2; exit 1; }

# ── Accent expression, generated from schemes/ ───────────────────────────────
# Collect "ORDER<TAB>GLOB<TAB>ACCENT" by sourcing each scheme in a subshell.
rows="$(
  for f in "$SCHEMES_DIR"/*.scheme; do
    [ -e "$f" ] || continue
    ( unset GLOB ACCENT ORDER LABEL; . "$f"
      : "${GLOB:?$f: GLOB unset}" "${ACCENT:?$f: ACCENT unset}"
      printf '%s\t%s\t%s\n' "${ORDER:-50}" "$GLOB" "$ACCENT" )
  done
)"
[ -n "$rows" ] || { echo "build.sh: no schemes in $SCHEMES_DIR" >&2; exit 1; }

# Wrap from the innermost default outward. Process highest ORDER first so the
# lowest-ORDER scheme ends up outermost — i.e. checked first at runtime.
ACC="$DEFAULT_ACCENT"
while IFS="$(printf '\t')" read -r _ord glob acc; do
  [ -n "$glob" ] || continue
  ACC="#{?#{m:${glob},#S},${acc},${ACC}}"
done < <(printf '%s\n' "$rows" | sort -rn -k1,1)

# ── status-right, assembled to match the selected widget ─────────────────────
SEPL="$(printf '\356\202\262')"   # U+E0B2 left-pointing powerline separator
load_seg="#[fg=#3c3836,bg=#282828]${SEPL}#[bg=#3c3836,fg=#ebdbb2] #(~/.tmux/bin/load.sh) "
if [ "$WIDGET" = "none" ]; then
  prevbg="#3c3836"; mid_seg=""
else
  prevbg="#504945"
  mid_seg="#[fg=#504945,bg=#3c3836]${SEPL}#[bg=#504945,fg=#ebdbb2] #(~/.tmux/bin/${WIDGET}.sh) "
fi
clock_seg="#[fg=${ACC},bg=${prevbg}]${SEPL}#[bg=${ACC},fg=#1d2021,bold] %l:%M %p #[default]"
SR="${load_seg}${mid_seg}${clock_seg}"

# ── Render (literal substitution — no sed metacharacter escaping needed) ─────
content="$(cat "$TEMPLATE")"
content="${content//@@ACCENT@@/$ACC}"
content="${content//@@STATUS_RIGHT@@/$SR}"
content="${content//@@SCROLL_LINES@@/$SCROLL_LINES}"

mkdir -p "$OUT_DIR"
schemes_list="$(ls "$SCHEMES_DIR"/*.scheme 2>/dev/null | xargs -n1 basename | tr '\n' ' ')"
{
  echo "# ===== GENERATED by build.sh — DO NOT EDIT. Edit common/tmux.conf.in ====="
  echo "# widget=${WIDGET}  scroll-lines=${SCROLL_LINES}  schemes: ${schemes_list}"
  printf '%s\n' "$content"
} > "$OUT"

echo "built $OUT  (widget=$WIDGET)"
